BROKER='192.168.10.10'
MQTT_ID='CUS10'
JS_TOPIC='/JOYSTICK'
MODBUS_TOPIC='/MODBUS'
DIST_TOPIC='/R/S/D/distanz'
LASERCMD_TOPIC='/C/S/D'
INKLINX_TOPIC='/R/S/I/X'
HUB_TOPIC='/HUB'
CD_TOPIC='/CD'
CS_TOPIC='/CS'
KS_TOPIC='/KS'
KD_TOPIC='/KD'
LICHT_TOPIC='/LICHT'
KAMERALICHT_TOPIC='/C/A/KAMERALICHT'
OS_TOPIC='/OS'
INIT_TOPIC='/INIT'
JOYSTICKINITRAW_TOPIC='/RAW'
JOYSTICKVAL_TOPIC='/VAL'
JOYSTICKMODBUSVR150_TOPIC='/VR150'
MQTT_JoystickRawTimer= 5 #sec
MQTT_JoystickTimer=.1 #sec
Lichttimer=.1
LICHTPWMSTEPS=5
LICHTSCHWELLENWERTJOYST_OBEN=650
LICHTSCHWELLENWERTJOYST_UNTEN=350

ADC_REF=5.0 #Referenzspannung, anpassen falls nötig
joystickoffset_zul=40
joystickcalib_offset_zul=35

# Mapping von Namen zu Kanalnummern
channel_mapping = {
    'CS': 0,
    'HUB': 1,
    'CD': 2,
    'LICHT': 3,
    'KS': 4,
    'KD': 5
}

PINO_JOYSTICKINIT=5
PINO_ROBOTERREFERENZIERT=23
PINO_ROBOTERKOMMUNIKATION=15
PINI_REFPARK=21
PINI_ROBOTERANGESTECKT=20
PINO_ROBOTERVERBUNDENLED=8
PINO_REFPARKFAHRTLED=24

CD_OFFSET=17000
CS_GEAR=100
CS_USTEPS=32
INKLINX_CORR=0.62

